server.port=8080

db.url=jdbc:mysql://localhost:3306/auction_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
db.user=root
db.password=123456789
db.pool.size=10
db.pool.max=20

antisniping.window.seconds=30
antisniping.extend.seconds=60
antisniping.max.extensions=5

dev.mode=true