package com.auction.enums;

public enum RequestType {
    LOGIN, REGISTER, LOGOUT,
    GET_AUCTIONS, GET_AUCTION_DETAIL,
    CREATE_AUCTION, UPDATE_AUCTION, DELETE_AUCTION,
    PLACE_BID, SET_AUTO_BID, CANCEL_AUTO_BID,
    SUBSCRIBE_AUCTION, UNSUBSCRIBE_AUCTION,
    GET_PROFILE, UPDATE_PROFILE, GET_MY_BIDS,
    ADMIN_GET_USERS, ADMIN_BAN_USER,
    ADMIN_UNBAN_USER, ADMIN_FORCE_CLOSE, ADMIN_GET_STATS
}