<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
         http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <!-- Phiên bản model của Maven -->
    <modelVersion>4.0.0</modelVersion>

    <!-- Nếu project của bạn là multi-module thì cần parent -->
    <parent>
        <groupId>com.auction</groupId>
        <artifactId>AuctionV1</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <!-- Tên module server -->
    <artifactId>auction-server</artifactId>

    <!-- Các thư viện module server cần dùng -->
    <dependencies>

        <!-- Phụ thuộc vào module shared để dùng User, DTO chung nếu có -->
        <dependency>
            <groupId>com.auction</groupId>
            <artifactId>auction-shared</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- MySQL JDBC Driver: giúp Java kết nối tới MySQL -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>8.4.0</version>
        </dependency>

    </dependencies>

</project>